### ISSUE TITLE
自动更新报错

### ISSUE THREAD

**Issue by weiyidu** [sprov065/x-ui#1]
> /dev/fd/63: line 1: syntax error near unexpected token `<'
/dev/fd/63: line 1: `<!DOCTYPE html><html class="html" lang="zh-CN"><head><meta charset="UTF-8"><link rel="profile" href="https://gmpg.org/xfn/11"><meta name='robots' content='noindex, follow' /><meta name="viewport" content="width=device-width, initial-scale=1"><link media="all" href="https://blog.sprov.xyz/wp-content/cache/autoptimize/css/autoptimize_8bc8a88a807b19123bc348d420c91fa0.css" rel="stylesheet" /><title>(/ﾟДﾟ)/没找到页面 | sprov</title><meta property="og:locale" content="zh_CN" /><meta property="og:title" content="(/ﾟДﾟ)/没找到页面 | sprov" /><meta property="og:site_name" content="sprov" /> <script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":["Person","Organization"],"@id":"https://blog.sprov.xyz/#/schema/person/3ff4dc3ee1dfc5c5cd967d035af1dde1","name":"sprov","image":{"@type":"ImageObject","@id":"https://blog.sprov.xyz/#personlogo","inLanguage":"zh-CN","url":"https://blog.sprov.xyz/wp-content/uploads/2019/01/f0288b435079a664c49b4ce8aae1403e.jpg","contentUrl":"https://blog.sprov.xyz/wp-content/uploads/2019/01/f0288b435079a664c49b4ce8aae1403e.jpg","caption":"sprov"},"logo":{"@id":"https://blog.sprov.xyz/#personlogo"}},{"@type":"WebSite","@id":"https://blog.sprov.xyz/#website","url":"https://blog.sprov.xyz/","name":"sprov","description":"linux\u6280\u672f\u535a\u5ba2","publisher":{"@id":"https://blog.sprov.xyz/#/schema/person/3ff4dc3ee1dfc5c5cd967d035af1dde1"},"inLanguage":"zh-CN"}]}</script> <link rel='dns-prefetch' href='//s.w.org' /><link rel="alternate" type="application/rss+xml" title="sprov &raquo; Feed" href="https://blog.sprov.xyz/feed/" /><link rel="alternate" type="application/rss+xml" title="sprov &raquo; 评论Feed" href="https://blog.sprov.xyz/comments/feed/" /> <script src="//www.googletagmanager.com/gtag/js?id=UA-137403879-1" type="text/javascript" data-cfasync="false"></script> <script type="text/javascript" data-cfasync="false">var em_version = '6.7.0';'

**Comment by sprov065** [comment]
没有正式发布，不支持这个功能
