### ISSUE TITLE
x-ui & aliyun 【轻量云服务器】

### ISSUE THREAD

**Issue by sinlee1** [sprov065/x-ui#10]
问题：
 - 昨天新买的测试机搭建在Ubuntu 20.04下，内核更新到新版
 
![image](https://user-images.githubusercontent.com/29684167/122330250-69e20a00-cf65-11eb-8767-bf48a95e9e37.png)

- 防火墙端口全部开放

![image](https://user-images.githubusercontent.com/29684167/122330304-81b98e00-cf65-11eb-876c-27e4d6fec36d.png)

- 流量一切正常
![image](https://user-images.githubusercontent.com/29684167/122330465-d230eb80-cf65-11eb-8c82-9e2e937d9cef.png)

- 但通过V2rayN测试发现却无法正常回连，提示请求失败，但我本地telnet的方式却都是正常的。

![image](https://user-images.githubusercontent.com/29684167/122330679-35bb1900-cf66-11eb-9ec5-3f29187af685.png)

- V2rayN路由设置为绕过大陆

**Comment by sprov065** [comment]
如果是自己配置错误导致无法使用的问题不要在这里问，自行解决

如果你觉得配置生成有误，请指出错误所在

**Comment by sinlee1** [comment]
刚重复测试了很多次，确认配置没有问题，出现时而正常使用，时而又无法正常连接，难道是机器问题？我重新换个操作系统版本试试看
