### ISSUE TITLE
入站列表内，流量统计有误

### ISSUE THREAD

**Issue by hhhkkk520** [sprov065/x-ui#15]
系统：Centos 7.8 / Debian 10
内核：Xray
问题描述：入站列表内的流量统计不准确，上传流量数据偏差过大，几乎不统计
<img width="389" alt="截屏2021-06-18 01 17 43" src="https://user-images.githubusercontent.com/52115472/122483570-2b833400-cfd3-11eb-9b04-78bb97daa19d.png">
这是我探针的流量统计，可以看到下载13GB，上传15GB，数据比较合理
<img width="261" alt="截屏2021-06-18 01 17 50" src="https://user-images.githubusercontent.com/52115472/122483615-48b80280-cfd3-11eb-99ce-d996ce74bf1d.png">
这是面板内的数据统计，可以看到下载偏差不大，可是上传的数据偏差太大了并且不合理，在下载有12GB的情况下上传不应该只有这么一点

另一台Debian 10系统的XuI面板也有同样问题
<img width="240" alt="截屏2021-06-18 01 22 02" src="https://user-images.githubusercontent.com/52115472/122483802-ac423000-cfd3-11eb-9ed1-b7adc02ef694.png">

**Comment by sprov065** [comment]
没有问题，纯属自己的理解有误
