### ISSUE TITLE
启动失败，日志如下，x-ui版本0.20, VPS亚马逊云

### ISSUE THREAD

**Issue by michealhansun** [sprov065/x-ui#17]
---------- System Information ----------
 OS      : Debian GNU/Linux 10
 Arch    : x86_64 (64 Bit)
 Kernel  : 4.19.0-16-cloud-amd64

面板状态: 未运行
是否开机自启: 是
xray 状态: 未运行

请输入选择 [0-14]: 11
-- Logs begin at Sat 2021-06-19 03:37:59 UTC. --
Jun 19 06:14:15 ip-172-31-17-42 systemd[1]: Started x-ui Service.
Jun 19 06:14:15 ip-172-31-17-42 systemd[12042]: x-ui.service: Changing to the requested working directory failed: No such file or directory
Jun 19 06:14:15 ip-172-31-17-42 systemd[12042]: x-ui.service: Failed at step CHDIR spawning /usr/local/x-ui/x-ui: No such file or directory
Jun 19 06:14:15 ip-172-31-17-42 systemd[1]: x-ui.service: Main process exited, code=exited, status=200/CHDIR
Jun 19 06:14:15 ip-172-31-17-42 systemd[1]: x-ui.service: Failed with result 'exit-code'.

**Comment by lacafjh** [comment]
同样的报错
```
-- Logs begin at Thu 2021-06-24 10:31:42 CST. --
Jun 24 10:31:44 Host-name systemd[1]: Started x-ui Service.
Jun 24 10:31:44 Host-name systemd[482]: x-ui.service: Changing to the requested working directory failed: No such file or directory
Jun 24 10:31:44 Host-name systemd[482]: x-ui.service: Failed at step CHDIR spawning /usr/local/x-ui/x-ui: No such file or directory
Jun 24 10:31:44 Host-name systemd[1]: x-ui.service: Main process exited, code=exited, status=200/CHDIR
Jun 24 10:31:44 Host-name systemd[1]: x-ui.service: Failed with result 'exit-code'.
```

**Comment by michealhansun** [comment]
没找到解决方案，重新安装就可以了

**Comment by lacafjh** [comment]
> 没找到解决方案，重新安装就可以了

我也确认了重装以后问题就没了，很神奇

**Comment by sprov065** [comment]
没有安装成功

**Comment by lacafjh** [comment]
> 没有安装成功

可能和我第一次是用 sudo 装的有关系？我刚刚直接切到 root 安装的

**Comment by lacafjh** [comment]
> 没有安装成功

这两天又出现同样的问题，怀疑是和 Caddy v2 有关系。我在更新 Caddyfile 上传之后就出现了这个报错。

**Comment by neowx** [comment]
> > 没有安装成功
> 
> 这两天又出现同样的问题，怀疑是和 Caddy v2 有关系。我在更新 Caddyfile 上传之后就出现了这个报错。
x-ui 有bug ，关闭自动启动 会删除 /usr/local/x-ui 目录文件 。导致无法重现启动

**Comment by neowx** [comment]
> > 没有安装成功
> 
> 这两天又出现同样的问题，怀疑是和 Caddy v2 有关系。我在更新 Caddyfile 上传之后就出现了这个报错。


x-ui 有bug ，关闭自动启动 会删除 /usr/local/x-ui 目录文件 。导致无法重现启动
