### ISSUE TITLE
vless+ws在shadowrocket的连接问题

### ISSUE THREAD

**Issue by Tobylive** [sprov065/x-ui#22]
感谢大佬的新面板，很好用。
就是使用过程中遇到个奇怪的地方，vless+ws，同一个号在shadowrocket同一个新版本下，有的手机可以连上，有的手机连不上。电脑和安卓上使用则没有这个问题。

另外，vmess+ws的话，shadowrocket/电脑/安卓都是正常连接。

**Comment by sprov065** [comment]
与面板无关
