### ISSUE TITLE
生成xray配置文件失败

### ISSUE THREAD

**Issue by Smilence-Love** [sprov065/x-ui#3]
直接上图：
环境：
GCP - Debain 10
配置啥的，都是从v2-ui上拷贝过来的
![Pic1](https://user-images.githubusercontent.com/55685347/121321933-1e19da00-c941-11eb-858e-9761acf0995e.png)
![Pic2](https://user-images.githubusercontent.com/55685347/121340879-ab195f00-c952-11eb-81bf-506f739237e2.png)

**Comment by sprov065** [comment]
监听 ip 不为空的时候没有处理正确，下个版本修复
