### ISSUE TITLE
web界面重启面板后,xray状态会出现error,然后再入站协议中随便添加一个协议后恢复running

### ISSUE THREAD

**Issue by CoreCodeJOJO** [sprov065/x-ui#34]
任何由于自己的配置错误导致的情况，请自行解决，issues 只用于解决面板自身的 bug

如果你确定面板的功能实现有 bug，请尽可能提供更多更精确的描述信息、复现方法与复现结果等等，而不是草草一句话了事，这对于问题的解决没有帮助

提问的艺术: https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by wosiwq** [comment]
可稳定复现

**Comment by neowx** [comment]
测试稳定重现， centOS7

**Comment by phpnbw** [comment]
一样，我也遇到了这个问题，新安装的面板，只要重启了。面板首页那里的x2ray状态就会显示error。

**Comment by sprov065** [comment]
修复
