### ISSUE TITLE
出现 vmess 无法连接，且 x-ui 入站列表无法删除新建的入站子项

### ISSUE THREAD

**Issue by zondaOf2012** [sprov065/x-ui#36]
你好，最近新入手了一个 VPS 的 IP 地址，确认本地可以 ping 通，且按照最新的 v2-ui 和 x-ui 的指引文档完成了安装，对应的网站 http:<ip>:65432 或者 http:<ip>:54321 都可以登录成功并看到相关面板，但是出现了 vmess 无法连接，下面是相关信息

服务器系统版本:

> NAME="CentOS Linux"
> VERSION="8 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="8"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="CentOS Linux 8 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:8"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-8"
> CENTOS_MANTISBT_PROJECT_VERSION="8"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="8"

已经运行了 chronyc 同步了 UTC 

> 
> chronyc tracking
> Reference ID    : A29FC801 (time.cloudflare.com)
> Stratum         : 4
> Ref time (UTC)  : Mon Jul 12 03:02:49 2021
> System time     : 0.000000100 seconds fast of NTP time
> Last offset     : -0.000100280 seconds
> RMS offset      : 0.000100280 seconds
> Frequency       : 0.032 ppm slow
> Residual freq   : -0.316 ppm
> Skew            : 0.043 ppm
> Root delay      : 0.030313971 seconds
> Root dispersion : 0.000807909 seconds
> Update interval : 1.6 seconds
> Leap status     : Normal

> timedatectl
>                Local time: Sun 2021-07-11 23:24:33 EDT
>            Universal time: Mon 2021-07-12 03:24:33 UTC
>                  RTC time: Mon 2021-07-12 03:24:31
>                 Time zone: America/New_York (EDT, -0400)
> System clock synchronized: yes
>               NTP service: active
>           RTC in local TZ: no

我另一个 vps 去年使用大神你的 v2-ui 搭建的是可以正常连接的，当时的系统时 centOS7 面板显示的是 v2ray

然上面这个系统时 centOS 8 面板显示的是 xray

不知道是不是这个最新的有问题

-------------------------

此外，x-ui 的账号列表，相比 v2-ui 没有二维码和拷贝链接功能，也没有删除新建账号功能 期待大神的更新和回复

**Comment by lyzcren** [comment]
请先确认防火墙设置，确认下节点对应的端口是否已经放行。

**Comment by zondaOf2012** [comment]
@lyzcren 感谢回复~~ 

嗯,  已经通过命令 firewall-cmd --query-port=xxxx/tcp 确定 65432、54321 都已经放行了，而且已经可以打开 http://<我的IP地址>:54321/xui/ 这个页面了，只是在“入站列表”生成账号后，对应的 vmess 没法连接

**Comment by zondaOf2012** [comment]
哦，我明白你的意思了，vmess 对应的端口没有打开，现在可以了，感谢大佬的回复。。。。

**Comment by lyzcren** [comment]
记得把issue关掉

**Comment by zondaOf2012** [comment]
好的，此外，没有删除和二维码，是因为网页子项要左右拖动一下，才可以看到，是我没太注意哈~~ 希望遇到同样的问题的小伙伴记得左右移动一下

<img width="608" alt="9f40bd5d-f20e-4355-b37a-a3ddfdf1c8b5" src="https://user-images.githubusercontent.com/3021796/125238692-27201180-e31a-11eb-8569-32156cf8d292.png">

就可以了，再次感谢大佬 @lyzcren
