### ISSUE TITLE
CentOS 8.3 一键安装成功，但是监听仅使用了IPV6导致IPV4访问不通

### ISSUE THREAD

**Issue by gitLinan** [sprov065/x-ui#38]
![image](https://user-images.githubusercontent.com/33097694/126277455-8a68b931-b9de-4c5f-96d3-95296c4f407e.png)
不知道是不是问题

**Comment by sprov065** [comment]
众所周知，监听 [:::] 包含所有ipv4地址

**Comment by xhunmon** [comment]
端口没开放吧？
试一下：/sbin/iptables -I INPUT -p tcp --dport 54321 -j ACCEPT

我的vps重新导致端口关闭了。
