### ISSUE TITLE
使用一段时间后，内核自动掉线

### ISSUE THREAD

**Issue by if1y** [sprov065/x-ui#39]
从v2-ui迁移过来，之前一直使用正常，切到x-ui后，运行一段时间（大概2天左右，未明确计算），内核会自动掉线，查看xray状态显示`未运行`。
此时只能通过重启的方式来恢复内核运行。

一种可能的猜测是128MB内存太小导致的。但目前的正常占用是50MB，之前v2-ui运行占用是70-90MB左右，甚至之前更高也没自动退出，所以这种猜测也不是很准确。

或许可以参考multi-vr2ay的方法，增加一个定时保活的功能。
目前我暂时考虑通过增加一条crontab来定时重启以解决这个问题。

**Comment by sprov065** [comment]
x-ui 0.3.0 已加入自动保护 xray 进程

**Comment by if1y** [comment]
谢谢修复，由于需要时间测试，暂时没有回复处理。
既然目前issue已经关闭了，那么如果后续发现问题再说。
