### ISSUE TITLE
X-UI开的代理不支持本机内网代理吗？

### ISSUE THREAD

**Issue by ShenHai9** [sprov065/x-ui#42]
想通过X-UI开的代理实现访问代理机的内网，目前X-UI开出来的代理似乎会拒绝连通代理机自身的内部网络。

请问可以让其开出来的代理能够访问代理机自身的内部网络吗。

**Comment by ShenHai9** [comment]
例如：

设备A：此时处于外部网络的一台设备。
设备B：安装了的X-UI的代理机。
设备C：另一台服务器。

此时只有设备B和设备C处于同一个局域网。

设备A如何通过连接设备B的代理，访问设备C（就是访问设备B、C所在的局域网）。

**Comment by yoyoll** [comment]
x-ui只是一个简单面板  估计是不会出现这样功能 更多定制需求功能应该上专业

**Comment by ShenHai9** [comment]
> x-ui只是一个简单面板 估计是不会出现这样功能 更多定制需求功能应该上专业

**Comment by ShenHai9** [comment]
> x-ui只是一个简单面板 估计是不会出现这样功能 更多定制需求功能应该上专业

**Comment by ShenHai9** [comment]
> x-ui只是一个简单面板 估计是不会出现这样功能 更多定制需求功能应该上专业

其实这应该是每一个代理都能实现的功能，比如原生的Socks5，我觉得应该是作者处于安全考虑在某些方面禁用掉了访问本机的内部网络。

**Comment by sprov065** [comment]
看看 xray 配置模板就懂了
