### ISSUE TITLE
希望增加单端口多用户的支持

### ISSUE THREAD

**Issue by anbell2** [sprov065/x-ui#6]
目前我是几个用户合租的VPS，用的vless+ws+tls模式，用nginx监听443来分流。
我几个用户都是用的同一配置，只是UUID不同。
你之前的v2-ui单端口只能一个用户，我没法使用。

希望增加单端口多用户的支持，并能分别计流。

**Comment by sprov065** [comment]
既要保证完善的单端口、多端口多用户功能，又要保持配置的绝对灵活性，这两样都要满足对于 ui 来说并不好做

**Comment by anbell2** [comment]
可以参照这个的改进版https://github.com/Nick-Hopps/v2-ui-plus

**Comment by anbell2** [comment]
我目前使用的是jrohy大神的多用户脚本，是可以单端口多用户的，只是没有面板，用的SSH
https://github.com/Jrohy/multi-v2ray

**Comment by anbell2** [comment]
我目前使用的是jrohy大神的多用户脚本，是可以单端口多用户的，只是没有面板，用的SSH
https://github.com/Jrohy/multi-v2ray

**Comment by anbell2** [comment]
对于用户来讲，就是在单端口添加多用户时，需要自己把握必需配置一致，这个提示一下用户，让用户来做选择吧，谢谢大神。

**Comment by sprov065** [comment]
> 对于用户来讲，就是在单端口添加多用户时，需要自己把握必需配置一致，这个提示一下用户，让用户来做选择吧，谢谢大神。

这种方式用起来相当难受，在没有良好的设计之前不会去强行实现这个功能

**Comment by anbell2** [comment]
另外，在安装XRAY的时候希望能使用root权限的脚本，这样装出来的XRAY才有权限读取由宝塔面板申请的证书。

**Comment by anbell2** [comment]
在没有单端口多用户时，用nginx监听443来分流，还可以设置多个分流。就是自己麻烦点。
如果一旦使用xray监听443来回落到nginx的话，多用户就没法玩了。

**Comment by anbell2** [comment]
我最理想的方式，就是用xray监听443来回落到nginx，然后xray使用宝塔申请的证书。
所以能做到这两点的话，需要单端口多用户的支持，以及root权限版的xray

**Comment by BrunuhVille** [comment]
> 我目前使用的是jrohy大神的多用户脚本，是可以单端口多用户的，只是没有面板，用的SSH
> https://github.com/Jrohy/multi-v2ray

你直接用他的trojan面板不就好了。。

**Comment by anbell2** [comment]
> > 我目前使用的是jrohy大神的多用户脚本，是可以单端口多用户的，只是没有面板，用的SSH 
> > https://github.com/Jrohy/multi-v2ray
> 
> 你直接用他的木马面板不就好了。。

我不用TJ，我用xray

**Comment by alegoho** [comment]
我支持这个功能，这功能太方便了
