### ISSUE TITLE
X-ui control panel too slow!!!

### ISSUE THREAD

**Issue by yhussy** [sprov065/x-ui#7]
Hi,
Big thanks for this great work )

1- X-ui control panel loading is slower than v2-ui !!!!
2- After activating swap memory, its not work.
3- Account list not showing account names "remark" , just ID numbers!!!

**Comment by sprov065** [comment]
1和3会在下个版本优化

关于第2点，请提供重现方式以及截图

**Comment by yhussy** [comment]
Thanks

> 1 and 3 will be optimized in the next version
> 
> Regarding point 2, please provide a reproduction method and screenshots

Thanks a lot my friend you fix every thing after update to 0.2.0 (^_^)
