### ISSUE TITLE
找了半天，没找到x-ui版本号的地方；x-ui（0.2.0）带的更新功能，还是不能用。

### ISSUE THREAD

**Issue by xKoding** [sprov065/x-ui#9]
1. 如题！
现在在新的VPS上安装x-ui，没找到版本号的地方。。很不方便
比如：重新运行安装的脚本，不知是否x-ui更新了。

bash <(curl -Ls https://raw.githubusercontent.com/sprov065/x-ui/master/install.sh) 0.1.0
安装完毕
bash <(curl -Ls https://raw.githubusercontent.com/sprov065/x-ui/master/install.sh) 0.2.0
再次运行完毕，咋能看出来现在用的是0.2.0版本呢？

2. 更新的功能，这个是怎么个情况？（GCP-Debian10，先安装了0.1.0 ，再运行脚本，安装了0.2.0；在0.2.0上运行的更新选项）

![Update](https://user-images.githubusercontent.com/85656790/122330736-48cde900-cf66-11eb-9204-5061301fd8de.png)

**Comment by sprov065** [comment]
重复问题 https://github.com/sprov065/x-ui/issues/1

**Comment by XXFilled** [comment]
> 
> 
> 重复问题 #1

恩。这个我知道，但提示的信息不一样了，我还以为已经fix了。。。

1. 版本号的问题呢？

**Comment by xKoding** [comment]
> 重复问题 #1

恩，这个我知道。就是现在的提示信息不一样了，想double confirm一下。

那个版本号的问题呢？在面板上看不到版本，不知道是否需要re-install一下最新的版本。

**Comment by sprov065** [comment]
直接跑一下最新的安装命令就完事

**Comment by xKoding** [comment]
好吧~_~！
